---

ansible_user: Automation
ansible_ssh_pass: Automation1
ansible_port: 22
ansible_connection: network_cli
ansible_network_os: cisco.iosxr.iosxr


interfaces:
  - name: GigabitEthernet 0/0/0/0
    description: "link to pe1"
    ip_address: "1.101.1.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/1
    description: "link to pe2 "
    ip_address: "1.101.2.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/2
    description: "link to asbr1"
    ip_address: "1.101.3.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/3
    description: "link to asbr2"
    ip_address: "1.101.4.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/4
    description: "link to RR1"
    ip_address: "1.101.5.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/5
    description: "link to p2"
    ip_address: "1.101.11.1"
    subnet_mask: "255.255.255.0"
  - name: GigabitEthernet 0/0/0/6
    description: "link to p3"
    ip_address: "1.101.17.1"
    subnet_mask: "255.255.255.0"
  - name: Loopback 0
    description: "Main-Loopback"
    ip_address: "100.0.0.27"
    subnet_mask: "255.255.255.255"