---

ansible_user: Automation
ansible_ssh_pass: Automation1
ansible_port: 22
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios


interfaces:
  - name: GigabitEthernet 1
    description: "link to p1"
    ip_address: "2.201.7.2"
    subnet_mask: "255.255.255.0"
  - name: Loopback 0
    description: "Main-Loopback"
    ip_address: "100.0.0.38"
    subnet_mask: "255.255.255.255"