---

- name: show ntp
  hosts: edge,routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: show ntp stuff
      cisco.ios.ios_command:
        commands:
          - show ntp associations
          - show ntp status
      register: output

    - name: show output
      debug:
        msg: "{{ output.stdout_lines }}"  