---
- name: Configure OSPF on Cisco routers
  hosts: edge
  gather_facts: no
  vars_files:
    - vars/ospf_areas.yml

  tasks:
    - name: Enable OSPF process
      cisco.ios.ios_config:
        lines:
          - "router ospf {{ ospf_config.process_id }}"
        parents: []
      vars:
        ospf_config: "{{ ospf_areas | selectattr('router', 'equalto', inventory_hostname) | first }}"
      tags: ospf_process

    - name: Add OSPF networks
      cisco.ios.ios_config:
        lines:
          - "network {{ network.network }} {{ network.wildcard }} area {{ ospf_config.area }}"
        parents: "router ospf {{ ospf_config.process_id }}"
      vars:
        ospf_config: "{{ ospf_areas | selectattr('router', 'equalto', inventory_hostname) | first }}"
      loop: "{{ ospf_config.networks }}"
      loop_control:
        loop_var: network
      tags: ospf_networks