---

- name: show interface
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
    - name: confirm interface
      cisco.ios.ios_command:
        commands:
          - show interface description
          - show ip interface brief | inc up
      register: youtube

    - name: display output
      debug:
        msg: "{{ youtube.stdout_lines }}"