---

ansible_user: YouTube
ansible_ssh_pass: YouTube1
ansible_port: 22
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios

interfaces:
  - name: GigabitEthernet 2
    description: "Link to Mancheater"
    ip_address: 10.0.1.1
    subnet_mask: 255.255.255.0

  - name: Loopback 0
    description: "MGMT loopback"
    ip_address: 100.100.100.1
    subnet_mask: 255.255.255.255

ospf_processes:
  - process_id: 2
    router_id: 100.100.100.1
    networks:
      - address: 10.0.1.0
        wildcard_bits: 0.0.0.255
        area: 1
      - address: 100.100.100.1
        wildcard_bits: 0.0.0.0
        area: 1