---

ansible_user: YouTube
ansible_ssh_pass: YouTube1
ansible_port: 22
ansible_connection: network_cli
ansible_network_os: cisco.ios.ios

interfaces:
  - name: GigabitEthernet 2
    description: "Link to Asia"
    ip_address: 10.0.3.1
    subnet_mask: 255.255.255.0

  - name: Loopback 0
    description: "MGMT loopback"
    ip_address: 100.100.100.3
    subnet_mask: 255.255.255.255

ospf_processes:
  - process_id: 4
    router_id: 100.100.100.3
    networks:
      - address: 10.0.3.0
        wildcard_bits: 0.0.0.255
        area: 3
      - address: 100.100.100.3
        wildcard_bits: 0.0.0.0
        area: 3